- name: article
  comment: Article
  columns:
    - name: id
      type: text
      key: PRI
      comment: ID
      datatype: varchar
    - name: slug
      type: text
      key: MUL
      comment: Slug
      datatype: varchar
    - name: title
      type: text
      comment: Title
      datatype: varchar
    - name: filename
      type: text
      comment: Filename
      datatype: varchar
    - name: description
      type: text
      comment: Description
      datatype: varchar
    - name: date
      type: timestamp
      key: MUL
      comment: Date
      datatype: datetime
    - name: og_image
      type: text
      comment: Og Image
      datatype: varchar
    - name: layout
      type: text
      key: MUL
      comment: Layout
      datatype: varchar
    - name: source
      type: text
      comment: Source
      datatype: varchar
    - name: url
      type: text
      comment: URL
      datatype: varchar
    - name: draft
      type: integer
      key: MUL
      comment: Draft
      datatype: bigint
      size: 8
    - name: created_at
      type: timestamp
      key: MUL
      comment: Created At
      datatype: datetime
    - name: updated_at
      type: timestamp
      comment: Updated At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_article_1
      columns:
        - id
      primary: true
      unique: true
    - name: idx_article_created_at
      columns:
        - created_at
    - name: idx_article_date
      columns:
        - date
    - name: idx_article_draft
      columns:
        - draft
    - name: idx_article_published
      columns:
        - draft
        - date
    - name: idx_article_layout
      columns:
        - layout
    - name: idx_article_slug
      columns:
        - slug
    - name: sqlite_autoindex_article_2
      columns:
        - slug
      unique: true
- name: migrations
  comment: Migrations
  columns:
    - name: project
      type: text
      key: PRI
      comment: Project
      datatype: varchar
    - name: filename
      type: text
      key: PRI
      comment: Filename
      datatype: varchar
    - name: statement_index
      type: integer
      comment: Statement Index
      datatype: bigint
      size: 8
    - name: status
      type: text
      comment: Status
      datatype: varchar
  indexes:
    - name: sqlite_autoindex_migrations_1
      columns:
        - project
        - filename
      primary: true
      unique: true
- name: setting
  comment: Setting
  columns:
    - name: user_id
      type: text
      key: PRI
      comment: User ID
      datatype: varchar
    - name: meta_lang
      type: text
      comment: Meta Lang
      datatype: varchar
    - name: meta_url
      type: text
      comment: Meta URL
      datatype: varchar
    - name: meta_author_name
      type: text
      comment: Meta Author Name
      datatype: varchar
    - name: meta_subtitle
      type: text
      comment: Meta Subtitle
      datatype: varchar
    - name: meta_headshot
      type: text
      comment: Meta Headshot
      datatype: varchar
    - name: posts_per_page
      type: integer
      comment: Posts Per Page
      datatype: bigint
      size: 8
    - name: social_github
      type: text
      comment: Social Github
      datatype: varchar
    - name: social_twitter
      type: text
      comment: Social Twitter
      datatype: varchar
    - name: social_linkedin
      type: text
      comment: Social Linkedin
      datatype: varchar
    - name: feature_webmention
      type: integer
      comment: Feature Webmention
      datatype: bigint
      size: 8
    - name: feature_pingback
      type: integer
      comment: Feature Pingback
      datatype: bigint
      size: 8
    - name: feature_comments
      type: integer
      comment: Feature Comments
      datatype: bigint
      size: 8
    - name: feature_rss
      type: integer
      comment: Feature Rss
      datatype: bigint
      size: 8
    - name: seo_title_suffix
      type: text
      comment: Seo Title Suffix
      datatype: varchar
    - name: seo_default_image
      type: text
      comment: Seo Default Image
      datatype: varchar
    - name: analytics_id
      type: text
      key: MUL
      comment: Analytics ID
      datatype: varchar
    - name: created_at
      type: timestamp
      comment: Created At
      datatype: datetime
    - name: updated_at
      type: timestamp
      comment: Updated At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_setting_1
      columns:
        - user_id
      primary: true
      unique: true
