package model

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"fmt"
	"strings"
	"time"
)

// QueryOption is implemented by each data model type.
type QueryOption interface {
	WithTable(name string) QueryOption
	WithColumns(cols []string) QueryOption
	WithWhere(clause string) QueryOption
	WithOrderBy(clause string) QueryOption
	WithLimit(start, offset int) QueryOption
	WithStatement(stmt string) QueryOption
}

// QueryConfig is a function-chaining SQL statement type.
type QueryConfig struct {
	Table       string
	Columns     []string
	Where       string
	OrderBy     string
	LimitStart  int
	LimitOffset int
	Statement   string
}

// WithTable will set the table name for the query.
func (q *QueryConfig) WithTable(name string) QueryOption {
	q.Table = name
	return q
}

// WithColumns will set the columns to use for the query.
func (q *QueryConfig) WithColumns(cols []string) QueryOption {
	q.Columns = cols
	return q
}

// WithWhere will set the where condition for the query.
func (q *QueryConfig) WithWhere(clause string) QueryOption {
	q.Where = clause
	return q
}

// WithOrderBy will set the order by clause for the query.
func (q *QueryConfig) WithOrderBy(clause string) QueryOption {
	q.OrderBy = clause
	return q
}

// WithLimit will set the limit clause parameters for the query.
func (q *QueryConfig) WithLimit(start, offset int) QueryOption {
	q.LimitStart = start
	q.LimitOffset = offset
	return q
}

// WithStatement will change the statement for the query.
func (q *QueryConfig) WithStatement(stmt string) QueryOption {
	q.Statement = stmt
	return q
}

// WithTable will set the table name for the query.
func WithTable(name string) QueryOption {
	return &QueryConfig{Table: name}
}

// WithColumns will set the columns to use for the query.
func WithColumns(cols []string) QueryOption {
	return &QueryConfig{Columns: cols}
}

// WithWhere will set the where condition for the query.
func WithWhere(clause string) QueryOption {
	return &QueryConfig{Where: clause}
}

// WithOrderBy will set the order by clause for the query.
func WithOrderBy(clause string) QueryOption {
	return &QueryConfig{OrderBy: clause}
}

// WithLimit will set the limit clause parameters for the query.
func WithLimit(start, offset int) QueryOption {
	return &QueryConfig{LimitStart: start, LimitOffset: offset}
}

// WithStatement will change the statement for the query.
func WithStatement(stmt string) QueryOption {
	return &QueryConfig{Statement: stmt}
}

// Apply will use passed query options to populate the query.
func (q *QueryConfig) Apply(opts ...QueryOption) *QueryConfig {
	cfg := *q
	for _, opt := range opts {
		o := opt.(*QueryConfig)
		if o.Table != "" {
			cfg.Table = o.Table
		}
		if len(o.Columns) > 0 {
			cfg.Columns = o.Columns
		}
		if o.Where != "" {
			cfg.Where = o.Where
		}
		if o.OrderBy != "" {
			cfg.OrderBy = o.OrderBy
		}
		if o.LimitOffset > 0 {
			cfg.LimitStart = o.LimitStart
			cfg.LimitOffset = o.LimitOffset
		}
		if o.Statement != "" {
			cfg.Statement = o.Statement
		}
	}
	return &cfg
}

// Migrations generated for db table `migrations`.
//
// Migrations.
type Migrations struct {
	// Project
	Project string `db:"project" json:"project"`

	// Filename
	Filename string `db:"filename" json:"filename"`

	// Statement Index
	StatementIndex int64 `db:"statement_index" json:"statement_index"`

	// Status
	Status string `db:"status" json:"status"`
}

// GetProject will return the value of Project.
func (m *Migrations) GetProject() string { return m.Project }

// GetFilename will return the value of Filename.
func (m *Migrations) GetFilename() string { return m.Filename }

// GetStatementIndex will return the value of StatementIndex.
func (m *Migrations) GetStatementIndex() int64 { return m.StatementIndex }

// GetStatus will return the value of Status.
func (m *Migrations) GetStatus() string { return m.Status }

// MigrationsTable is the name of the table in the DB.
const MigrationsTable = "`migrations`"

// MigrationsFields is a list of all columns in the DB table.
var MigrationsFields = []string{"project", "filename", "statement_index", "status"}

// MigrationsPrimaryFields are the primary key fields in the DB table.
var MigrationsPrimaryFields = []string{"project", "filename"}

// PulseDaily generated for db table `pulse_daily`.
//
// Pulse Daily.
type PulseDaily struct {
	// User ID
	UserID string `db:"user_id" json:"user_id"`

	// Stamp
	Stamp *time.Time `db:"stamp" json:"stamp"`

	// Count
	Count int64 `db:"count" json:"count"`
}

// GetUserID will return the value of UserID.
func (p *PulseDaily) GetUserID() string { return p.UserID }

// GetStamp will return the value of Stamp.
func (p *PulseDaily) GetStamp() *time.Time { return p.Stamp }

// SetStamp sets Stamp to the provided value.
func (p *PulseDaily) SetStamp(stamp time.Time) { p.Stamp = &stamp }

// GetCount will return the value of Count.
func (p *PulseDaily) GetCount() int64 { return p.Count }

// PulseDailyTable is the name of the table in the DB.
const PulseDailyTable = "`pulse_daily`"

// PulseDailyFields is a list of all columns in the DB table.
var PulseDailyFields = []string{"user_id", "stamp", "count"}

// PulseDailyPrimaryFields are the primary key fields in the DB table.
var PulseDailyPrimaryFields = []string{"user_id", "stamp"}

// PulseHourly generated for db table `pulse_hourly`.
//
// Pulse Hourly.
type PulseHourly struct {
	// User ID
	UserID string `db:"user_id" json:"user_id"`

	// Stamp
	Stamp *time.Time `db:"stamp" json:"stamp"`

	// Count
	Count int64 `db:"count" json:"count"`
}

// GetUserID will return the value of UserID.
func (p *PulseHourly) GetUserID() string { return p.UserID }

// GetStamp will return the value of Stamp.
func (p *PulseHourly) GetStamp() *time.Time { return p.Stamp }

// SetStamp sets Stamp to the provided value.
func (p *PulseHourly) SetStamp(stamp time.Time) { p.Stamp = &stamp }

// GetCount will return the value of Count.
func (p *PulseHourly) GetCount() int64 { return p.Count }

// PulseHourlyTable is the name of the table in the DB.
const PulseHourlyTable = "`pulse_hourly`"

// PulseHourlyFields is a list of all columns in the DB table.
var PulseHourlyFields = []string{"user_id", "stamp", "count"}

// PulseHourlyPrimaryFields are the primary key fields in the DB table.
var PulseHourlyPrimaryFields = []string{"user_id", "stamp"}

// Insert starts building an INSERT INTO query.
func (m *Migrations) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (m *Migrations) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (m *Migrations) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (m *Migrations) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (p *PulseDaily) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: PulseDailyTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := PulseDailyFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (p *PulseDaily) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: PulseDailyTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (p *PulseDaily) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: PulseDailyTable}).Apply(opts...)
	cols := PulseDailyFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (p *PulseDaily) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: PulseDailyTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (p *PulseHourly) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: PulseHourlyTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := PulseHourlyFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (p *PulseHourly) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: PulseHourlyTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (p *PulseHourly) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: PulseHourlyTable}).Apply(opts...)
	cols := PulseHourlyFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (p *PulseHourly) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: PulseHourlyTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}
