---
version: "3"

# Setup GOTOOLCHAIN workaround for #75031:
# https://github.com/golang/go/issues/75031#issuecomment-3195256688

vars:
  name: app
  docker_image: internal/{{.name}}
  goversion:
    sh: go env GOVERSION
  toolchain: '{{.goversion}}+auto'

tasks:
  default:
    desc: "Run platform base"
    dotenv: [.env.run]
    cmds:
      - task: gen
      - task: fmt
      - CGO_ENABLED=0 go run ./cmd/{{.name}}

  fmt:
    desc: "Source code formatting"
    cmds:
      - goimports -w -local $(go list .) .
      - goimports-reviser -set-alias -format -imports-order "std,blanked,general,company,project" ./...
      - gofumpt -w .
      - go mod tidy

  gen:
    desc: "Generate code"
    cmds:
      - go generate ./...

  docker:
    desc: "Build docker image"
    cmds:
      - defer: rm {{.name}} -f
      - CGO_ENABLED=0 go build ./cmd/{{.name}}
      - docker build --no-cache -t {{.docker_image}} -f docker/Dockerfile .

  clean:
    desc: "Clean build assets"
    cmds:
      - task: gen
      - task: fmt
      - go clean -cache
      - go clean -testcache
      - rm -f ./{{.name}} pkg.cov pkg.cov.json go-fsck.json
      - docker rmi -f {{.docker_image}}

  migrate:
    desc: "Run migrations"
    dotenv: [.env.run]
    cmds:
      - mig lint --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform" --schema platform
      - mig docs --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform" --schema platform --output=./modules/user/docs
      - mig gen --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform" --go.skip-json --schema platform --output=./modules/user/model
      - mig docs --db-driver sqlite --db-dsn="file:daily.db" --schema platform --output=./modules/daily/docs
      - mig gen --db-driver sqlite --db-dsn="file:daily.db" --go.skip-json --schema platform --output=./modules/daily/model

  migrate:email:
    desc: "Run email module migrations"
    dotenv: [.env.run]
    cmds:
      - mig docs --db-driver sqlite --db-dsn="file:email.db" --schema platform --output=./modules/email/docs
      - mig gen --db-driver sqlite --db-dsn="file:email.db" --go.skip-json --schema platform --output=./modules/email/model

  bench:
    desc: "Run benchmarks"
    dotenv: [.env.test]
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmd: go test -failfast -run='Bench.+' -bench=. -benchmem -cpu 1,2,4 -race -v ./...

  test:
    desc: "Run tests and collect coverage"
    dotenv: [.env.test]
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmds:
      - task: fmt
      - go test -failfast -race -count=1 -cover -coverpkg=./... -coverprofile=pkg.cov ./...

  integration:
    desc: "Run integration tests"
    vars:
      tags: integration
    dotenv: [.env.test]
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmds:
      - task: fmt
      - go test -tags '{{.tags}}' -failfast -race -count=1 -cover -coverpkg=./... -coverprofile=pkg.cov ./...

  test:email:
    desc: "Run email module tests with mailhog"
    dotenv: [.env.test]
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmds:
      - task: fmt
      - go test -tags integration -failfast -count=1 -cover -coverpkg=./... -v ./modules/email/...

  cover:
    desc: "Show source coverage"
    cmds:
      - go tool cover -func=pkg.cov | summary coverfunc --json > pkg.cov.json
      - go-fsck extract --pretty-json ./...
      - go-fsck coverage -c pkg.cov.json -o go-fsck.json
      - go-fsck coverage --template=docs/testing-coverage.md.tpl -v > docs/testing-coverage.md
      - perl -pi -e 's/github.com\/titpetric/titpetric/g' docs/testing-coverage.md
      - go-fsck docs --render imports > docs/imports.puml
      - go-fsck docs --render puml > docs/structure.puml
      - plantuml -tsvg docs/structure.puml
      - plantuml -tsvg docs/imports.puml

  uncover:
    desc: "Show uncovered source"
    cmd: uncover pkg.cov

  setup:
    desc: "Install dev tooling"
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
      - go install mvdan.cc/gofumpt@latest
      - go install -v github.com/incu6us/goimports-reviser/v3@latest

  up:
    desc: "Bring up docker env"
    cmd: docker compose up -d --remove-orphans --wait

  down:
    desc: "Bring down docker env"
    cmd: docker compose down
