package model

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"time"
)

// Migrations generated for db table `migrations`.
type Migrations struct {
	// Project
	Project string `db:"project"`

	// Filename
	Filename string `db:"filename"`

	// Statement Index
	StatementIndex int64 `db:"statement_index"`

	// Status
	Status string `db:"status"`
}

// GetProject will return the value of Project.
func (m *Migrations) GetProject() string { return m.Project }

// GetFilename will return the value of Filename.
func (m *Migrations) GetFilename() string { return m.Filename }

// GetStatementIndex will return the value of StatementIndex.
func (m *Migrations) GetStatementIndex() int64 { return m.StatementIndex }

// GetStatus will return the value of Status.
func (m *Migrations) GetStatus() string { return m.Status }

// MigrationsTable is the name of the table in the DB.
const MigrationsTable = "`migrations`"

// MigrationsFields is a list of all columns in the DB table.
var MigrationsFields = []string{"project", "filename", "statement_index", "status"}

// MigrationsPrimaryFields are the primary key fields in the DB table.
var MigrationsPrimaryFields = []string{"project"}

// Todo generated for db table `todo`.
type Todo struct {
	// ID
	ID string `db:"id"`

	// User ID
	UserID string `db:"user_id"`

	// Title
	Title string `db:"title"`

	// Completed
	Completed bool `db:"completed"`

	// Created At
	CreatedAt *time.Time `db:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at"`

	// Deleted At
	DeletedAt *time.Time `db:"deleted_at"`
}

// GetID will return the value of ID.
func (t *Todo) GetID() string { return t.ID }

// GetUserID will return the value of UserID.
func (t *Todo) GetUserID() string { return t.UserID }

// GetTitle will return the value of Title.
func (t *Todo) GetTitle() string { return t.Title }

// GetCompleted will return the value of Completed.
func (t *Todo) GetCompleted() bool { return t.Completed }

// GetCreatedAt will return the value of CreatedAt.
func (t *Todo) GetCreatedAt() *time.Time { return t.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (t *Todo) SetCreatedAt(stamp time.Time) { t.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (t *Todo) GetUpdatedAt() *time.Time { return t.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (t *Todo) SetUpdatedAt(stamp time.Time) { t.UpdatedAt = &stamp }

// GetDeletedAt will return the value of DeletedAt.
func (t *Todo) GetDeletedAt() *time.Time { return t.DeletedAt }

// SetDeletedAt sets DeletedAt to the provided value.
func (t *Todo) SetDeletedAt(stamp time.Time) { t.DeletedAt = &stamp }

// TodoTable is the name of the table in the DB.
const TodoTable = "`todo`"

// TodoFields is a list of all columns in the DB table.
var TodoFields = []string{"id", "user_id", "title", "completed", "created_at", "updated_at", "deleted_at"}

// TodoPrimaryFields are the primary key fields in the DB table.
var TodoPrimaryFields = []string{"id"}
