- name: migrations
  comment: Migrations
  columns:
    - name: project
      type: text
      key: PRI
      comment: Project
      datatype: varchar
    - name: filename
      type: text
      key: PRI
      comment: Filename
      datatype: varchar
    - name: statement_index
      type: integer
      comment: Statement Index
      datatype: bigint
      size: 8
    - name: status
      type: text
      comment: Status
      datatype: varchar
  indexes:
    - name: sqlite_autoindex_migrations_1
      columns:
        - project
        - filename
      primary: true
      unique: true
- name: todo
  comment: Todo
  columns:
    - name: id
      type: text
      key: PRI
      comment: ID
      datatype: char(26)
    - name: user_id
      type: text
      key: MUL
      comment: User ID
      datatype: char(26)
    - name: title
      type: text
      comment: Title
      datatype: varchar
    - name: completed
      type: boolean
      comment: Completed
      datatype: boolean
    - name: created_at
      type: timestamp
      comment: Created At
      datatype: datetime
    - name: updated_at
      type: timestamp
      comment: Updated At
      datatype: datetime
    - name: deleted_at
      type: timestamp
      comment: Deleted At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_todo_1
      columns:
        - id
      primary: true
      unique: true
