- name: migrations
  comment: Migrations
  columns:
    - name: project
      type: TEXT
      key: PRI
      comment: Project
      datatype: text
    - name: filename
      type: TEXT
      key: PRI
      comment: Filename
      datatype: text
    - name: statement_index
      type: INTEGER
      comment: Statement Index
      datatype: integer
    - name: status
      type: TEXT
      comment: Status
      datatype: text
  indexes:
    - name: sqlite_autoindex_migrations_1
      columns:
        - project
        - filename
      primary: true
      unique: true
- name: todo
  comment: Todo
  columns:
    - name: id
      type: CHAR(26)
      key: PRI
      comment: ID
      datatype: text
    - name: user_id
      type: CHAR(26)
      key: MUL
      comment: User ID
      datatype: text
    - name: title
      type: TEXT
      comment: Title
      datatype: text
    - name: completed
      type: BOOLEAN
      comment: Completed
      datatype: boolean
    - name: created_at
      type: DATETIME
      comment: Created At
      datatype: timestamp
    - name: updated_at
      type: DATETIME
      comment: Updated At
      datatype: timestamp
    - name: deleted_at
      type: DATETIME
      comment: Deleted At
      datatype: timestamp
  indexes:
    - name: sqlite_autoindex_todo_1
      columns:
        - id
      primary: true
      unique: true
