package model

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"fmt"
	"strings"
	"time"
)

type QueryOption interface {
	WithTable(name string) QueryOption
	WithColumns(cols []string) QueryOption
	WithWhere(clause string) QueryOption
	WithOrderBy(clause string) QueryOption
	WithLimit(start, offset int) QueryOption
	WithStatement(stmt string) QueryOption
}

type QueryConfig struct {
	Table       string
	Columns     []string
	Where       string
	OrderBy     string
	LimitStart  int
	LimitOffset int
	Statement   string
}

func (q *QueryConfig) WithTable(name string) QueryOption {
	q.Table = name
	return q
}

func (q *QueryConfig) WithColumns(cols []string) QueryOption {
	q.Columns = cols
	return q
}

func (q *QueryConfig) WithWhere(clause string) QueryOption {
	q.Where = clause
	return q
}

func (q *QueryConfig) WithOrderBy(clause string) QueryOption {
	q.OrderBy = clause
	return q
}

func (q *QueryConfig) WithLimit(start, offset int) QueryOption {
	q.LimitStart = start
	q.LimitOffset = offset
	return q
}

func (q *QueryConfig) WithStatement(stmt string) QueryOption {
	q.Statement = stmt
	return q
}

func WithTable(name string) QueryOption {
	return &QueryConfig{Table: name}
}

func WithColumns(cols []string) QueryOption {
	return &QueryConfig{Columns: cols}
}

func WithWhere(clause string) QueryOption {
	return &QueryConfig{Where: clause}
}

func WithOrderBy(clause string) QueryOption {
	return &QueryConfig{OrderBy: clause}
}

func WithLimit(start, offset int) QueryOption {
	return &QueryConfig{LimitStart: start, LimitOffset: offset}
}

func WithStatement(stmt string) QueryOption {
	return &QueryConfig{Statement: stmt}
}

func (q *QueryConfig) Apply(opts ...QueryOption) *QueryConfig {
	cfg := *q
	for _, opt := range opts {
		o := opt.(*QueryConfig)
		if o.Table != "" {
			cfg.Table = o.Table
		}
		if len(o.Columns) > 0 {
			cfg.Columns = o.Columns
		}
		if o.Where != "" {
			cfg.Where = o.Where
		}
		if o.OrderBy != "" {
			cfg.OrderBy = o.OrderBy
		}
		if o.LimitOffset > 0 {
			cfg.LimitStart = o.LimitStart
			cfg.LimitOffset = o.LimitOffset
		}
		if o.Statement != "" {
			cfg.Statement = o.Statement
		}
	}
	return &cfg
}

// User generated for db table `user`.
//
// Stores user profile information using ULID as primary key.
type User struct {
	// Primary key: ULID string
	ID string `db:"id"`

	// User first name
	FirstName string `db:"first_name"`

	// User last name
	LastName string `db:"last_name"`

	// Soft delete timestamp, NULL if active
	DeletedAt *time.Time `db:"deleted_at"`

	// Record creation timestamp
	CreatedAt *time.Time `db:"created_at"`

	// Record update timestamp
	UpdatedAt *time.Time `db:"updated_at"`
}

// GetID will return the value of ID.
func (u *User) GetID() string { return u.ID }

// GetFirstName will return the value of FirstName.
func (u *User) GetFirstName() string { return u.FirstName }

// GetLastName will return the value of LastName.
func (u *User) GetLastName() string { return u.LastName }

// GetDeletedAt will return the value of DeletedAt.
func (u *User) GetDeletedAt() *time.Time { return u.DeletedAt }

// SetDeletedAt sets DeletedAt to the provided value.
func (u *User) SetDeletedAt(stamp time.Time) { u.DeletedAt = &stamp }

// GetCreatedAt will return the value of CreatedAt.
func (u *User) GetCreatedAt() *time.Time { return u.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (u *User) SetCreatedAt(stamp time.Time) { u.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (u *User) GetUpdatedAt() *time.Time { return u.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (u *User) SetUpdatedAt(stamp time.Time) { u.UpdatedAt = &stamp }

// UserTable is the name of the table in the DB.
const UserTable = "`user`"

// UserFields is a list of all columns in the DB table.
var UserFields = []string{"id", "first_name", "last_name", "deleted_at", "created_at", "updated_at"}

// UserPrimaryFields are the primary key fields in the DB table.
var UserPrimaryFields = []string{"id"}

// UserAuth generated for db table `user_auth`.
//
// Stores user authentication credentials.
type UserAuth struct {
	// Reference to user.id (ULID)
	UserID string `db:"user_id"`

	// User email address, unique
	Email string `db:"email"`

	// Hashed password
	Password string `db:"password"`

	// Record creation timestamp
	CreatedAt *time.Time `db:"created_at"`

	// Record update timestamp
	UpdatedAt *time.Time `db:"updated_at"`
}

// GetUserID will return the value of UserID.
func (u *UserAuth) GetUserID() string { return u.UserID }

// GetEmail will return the value of Email.
func (u *UserAuth) GetEmail() string { return u.Email }

// GetPassword will return the value of Password.
func (u *UserAuth) GetPassword() string { return u.Password }

// GetCreatedAt will return the value of CreatedAt.
func (u *UserAuth) GetCreatedAt() *time.Time { return u.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (u *UserAuth) SetCreatedAt(stamp time.Time) { u.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (u *UserAuth) GetUpdatedAt() *time.Time { return u.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (u *UserAuth) SetUpdatedAt(stamp time.Time) { u.UpdatedAt = &stamp }

// UserAuthTable is the name of the table in the DB.
const UserAuthTable = "`user_auth`"

// UserAuthFields is a list of all columns in the DB table.
var UserAuthFields = []string{"user_id", "email", "password", "created_at", "updated_at"}

// UserAuthPrimaryFields are the primary key fields in the DB table.
var UserAuthPrimaryFields = []string{"user_id"}

// UserGroup generated for db table `user_group`.
//
// Stores user group information using ULID as primary key.
type UserGroup struct {
	// Primary key: ULID string
	ID string `db:"id"`

	// Group name/title
	Title string `db:"title"`

	// Record creation timestamp
	CreatedAt *time.Time `db:"created_at"`

	// Record update timestamp
	UpdatedAt *time.Time `db:"updated_at"`
}

// GetID will return the value of ID.
func (u *UserGroup) GetID() string { return u.ID }

// GetTitle will return the value of Title.
func (u *UserGroup) GetTitle() string { return u.Title }

// GetCreatedAt will return the value of CreatedAt.
func (u *UserGroup) GetCreatedAt() *time.Time { return u.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (u *UserGroup) SetCreatedAt(stamp time.Time) { u.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (u *UserGroup) GetUpdatedAt() *time.Time { return u.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (u *UserGroup) SetUpdatedAt(stamp time.Time) { u.UpdatedAt = &stamp }

// UserGroupTable is the name of the table in the DB.
const UserGroupTable = "`user_group`"

// UserGroupFields is a list of all columns in the DB table.
var UserGroupFields = []string{"id", "title", "created_at", "updated_at"}

// UserGroupPrimaryFields are the primary key fields in the DB table.
var UserGroupPrimaryFields = []string{"id"}

// UserGroupMember generated for db table `user_group_member`.
//
// Stores user memberships in groups using ULID for IDs.
type UserGroupMember struct {
	// Reference to user_group.id (ULID)
	UserGroupID string `db:"user_group_id"`

	// Reference to user.id (ULID)
	UserID string `db:"user_id"`

	// Timestamp when user joined the group
	JoinedAt *time.Time `db:"joined_at"`
}

// GetUserGroupID will return the value of UserGroupID.
func (u *UserGroupMember) GetUserGroupID() string { return u.UserGroupID }

// GetUserID will return the value of UserID.
func (u *UserGroupMember) GetUserID() string { return u.UserID }

// GetJoinedAt will return the value of JoinedAt.
func (u *UserGroupMember) GetJoinedAt() *time.Time { return u.JoinedAt }

// SetJoinedAt sets JoinedAt to the provided value.
func (u *UserGroupMember) SetJoinedAt(stamp time.Time) { u.JoinedAt = &stamp }

// UserGroupMemberTable is the name of the table in the DB.
const UserGroupMemberTable = "`user_group_member`"

// UserGroupMemberFields is a list of all columns in the DB table.
var UserGroupMemberFields = []string{"user_group_id", "user_id", "joined_at"}

// UserGroupMemberPrimaryFields are the primary key fields in the DB table.
var UserGroupMemberPrimaryFields = []string{"user_group_id", "user_id"}

// UserSession generated for db table `user_session`.
//
// Stores immutable user sessions with ULID IDs and expiration.
type UserSession struct {
	// Primary key: ULID string, also used as session token
	ID string `db:"id"`

	// Reference to user.id (ULID)
	UserID string `db:"user_id"`

	// Session expiration timestamp
	ExpiresAt *time.Time `db:"expires_at"`

	// Session creation timestamp
	CreatedAt *time.Time `db:"created_at"`
}

// GetID will return the value of ID.
func (u *UserSession) GetID() string { return u.ID }

// GetUserID will return the value of UserID.
func (u *UserSession) GetUserID() string { return u.UserID }

// GetExpiresAt will return the value of ExpiresAt.
func (u *UserSession) GetExpiresAt() *time.Time { return u.ExpiresAt }

// SetExpiresAt sets ExpiresAt to the provided value.
func (u *UserSession) SetExpiresAt(stamp time.Time) { u.ExpiresAt = &stamp }

// GetCreatedAt will return the value of CreatedAt.
func (u *UserSession) GetCreatedAt() *time.Time { return u.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (u *UserSession) SetCreatedAt(stamp time.Time) { u.CreatedAt = &stamp }

// UserSessionTable is the name of the table in the DB.
const UserSessionTable = "`user_session`"

// UserSessionFields is a list of all columns in the DB table.
var UserSessionFields = []string{"id", "user_id", "expires_at", "created_at"}

// UserSessionPrimaryFields are the primary key fields in the DB table.
var UserSessionPrimaryFields = []string{"id"}

func (u *User) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := UserFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (u *User) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (u *User) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserTable}).Apply(opts...)
	cols := UserFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *User) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *UserAuth) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserAuthTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := UserAuthFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (u *UserAuth) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserAuthTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (u *UserAuth) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserAuthTable}).Apply(opts...)
	cols := UserAuthFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *UserAuth) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserAuthTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *UserGroup) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserGroupTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := UserGroupFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (u *UserGroup) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserGroupTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (u *UserGroup) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserGroupTable}).Apply(opts...)
	cols := UserGroupFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *UserGroup) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserGroupTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *UserGroupMember) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserGroupMemberTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := UserGroupMemberFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (u *UserGroupMember) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserGroupMemberTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (u *UserGroupMember) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserGroupMemberTable}).Apply(opts...)
	cols := UserGroupMemberFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *UserGroupMember) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserGroupMemberTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *UserSession) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserSessionTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := UserSessionFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (u *UserSession) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserSessionTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (u *UserSession) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserSessionTable}).Apply(opts...)
	cols := UserSessionFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (u *UserSession) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserSessionTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}
