- name: migrations
  comment: Migrations
  columns:
    - name: project
      type: text
      key: PRI
      comment: Project
      datatype: varchar
    - name: filename
      type: text
      key: PRI
      comment: Filename
      datatype: varchar
    - name: statement_index
      type: integer
      comment: Statement Index
      datatype: bigint
      size: 8
    - name: status
      type: text
      comment: Status
      datatype: varchar
  indexes:
    - name: sqlite_autoindex_migrations_1
      columns:
        - project
        - filename
      primary: true
      unique: true
- name: user
  comment: User
  columns:
    - name: id
      type: text
      key: PRI
      comment: ID
      datatype: varchar
    - name: full_name
      type: text
      comment: Full Name
      datatype: varchar
    - name: username
      type: text
      comment: Username
      datatype: varchar
    - name: slug
      type: text
      key: MUL
      comment: Slug
      datatype: varchar
    - name: deleted_at
      type: timestamp
      key: MUL
      comment: Deleted At
      datatype: datetime
    - name: created_at
      type: timestamp
      comment: Created At
      datatype: datetime
    - name: updated_at
      type: timestamp
      comment: Updated At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_user_1
      columns:
        - id
      primary: true
      unique: true
    - name: idx_user_deleted_at
      columns:
        - deleted_at
    - name: idx_user_slug
      columns:
        - slug
      unique: true
- name: user_auth
  comment: User Auth
  columns:
    - name: user_id
      type: text
      key: PRI
      comment: User ID
      datatype: varchar
    - name: email
      type: text
      key: MUL
      comment: Email
      datatype: varchar
    - name: password
      type: text
      comment: Password
      datatype: varchar
    - name: created_at
      type: timestamp
      comment: Created At
      datatype: datetime
    - name: updated_at
      type: timestamp
      comment: Updated At
      datatype: datetime
    - name: activated_at
      type: timestamp
      comment: Activated At
      datatype: datetime
    - name: activation_token
      type: text
      key: MUL
      comment: Activation Token
      datatype: varchar
    - name: activation_sent_at
      type: timestamp
      comment: Activation Sent At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_user_auth_1
      columns:
        - user_id
      primary: true
      unique: true
    - name: idx_user_auth_activation_token
      columns:
        - activation_token
    - name: idx_user_auth_email
      columns:
        - email
      unique: true
- name: user_group
  comment: User Group
  columns:
    - name: id
      type: text
      key: PRI
      comment: ID
      datatype: varchar
    - name: title
      type: text
      comment: Title
      datatype: varchar
    - name: created_at
      type: timestamp
      comment: Created At
      datatype: datetime
    - name: updated_at
      type: timestamp
      comment: Updated At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_user_group_1
      columns:
        - id
      primary: true
      unique: true
- name: user_group_member
  comment: User Group Member
  columns:
    - name: user_group_id
      type: text
      key: PRI
      comment: User Group ID
      datatype: varchar
    - name: user_id
      type: text
      key: PRI
      comment: User ID
      datatype: varchar
    - name: joined_at
      type: timestamp
      comment: Joined At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_user_group_member_1
      columns:
        - user_group_id
        - user_id
      primary: true
      unique: true
    - name: idx_user_group_member_user_id
      columns:
        - user_id
- name: user_passkey
  comment: User Passkey
  columns:
    - name: id
      type: text
      key: PRI
      comment: ID
      datatype: varchar
    - name: user_id
      type: text
      key: MUL
      comment: User ID
      datatype: varchar
    - name: credential_id
      type: blob
      key: MUL
      comment: Credential ID
      datatype: blob
    - name: public_key
      type: blob
      comment: Public Key
      datatype: blob
    - name: attestation_type
      type: text
      comment: Attestation Type
      datatype: varchar
    - name: transport
      type: text
      comment: Transport
      datatype: varchar
    - name: sign_count
      type: integer
      comment: Sign Count
      datatype: bigint
      size: 8
    - name: created_at
      type: timestamp
      comment: Created At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_user_passkey_1
      columns:
        - id
      primary: true
      unique: true
    - name: idx_user_passkey_credential_id
      columns:
        - credential_id
      unique: true
    - name: idx_user_passkey_user_id
      columns:
        - user_id
- name: user_session
  comment: User Session
  columns:
    - name: id
      type: text
      key: PRI
      comment: ID
      datatype: varchar
    - name: user_id
      type: text
      key: MUL
      comment: User ID
      datatype: varchar
    - name: expires_at
      type: timestamp
      key: MUL
      comment: Expires At
      datatype: datetime
    - name: created_at
      type: timestamp
      comment: Created At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_user_session_1
      columns:
        - id
      primary: true
      unique: true
    - name: idx_user_session_expires_at
      columns:
        - expires_at
    - name: idx_user_session_user_id
      columns:
        - user_id
- name: user_token_revoked
  comment: User Token Revoked
  columns:
    - name: jti
      type: text
      key: PRI
      comment: Jti
      datatype: varchar
    - name: user_id
      type: text
      key: MUL
      comment: User ID
      datatype: varchar
    - name: expires_at
      type: timestamp
      key: MUL
      comment: Expires At
      datatype: datetime
    - name: created_at
      type: timestamp
      comment: Created At
      datatype: datetime
  indexes:
    - name: sqlite_autoindex_user_token_revoked_1
      columns:
        - jti
      primary: true
      unique: true
    - name: idx_user_token_revoked_expires_at
      columns:
        - expires_at
    - name: idx_user_token_revoked_user_id
      columns:
        - user_id
