package model

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"time"
)

// Migrations generated for db table `migrations`.
type Migrations struct {
	// Project
	Project string `db:"project"`

	// Filename
	Filename string `db:"filename"`

	// Statement Index
	StatementIndex int64 `db:"statement_index"`

	// Status
	Status string `db:"status"`
}

// GetProject will return the value of Project.
func (m *Migrations) GetProject() string { return m.Project }

// GetFilename will return the value of Filename.
func (m *Migrations) GetFilename() string { return m.Filename }

// GetStatementIndex will return the value of StatementIndex.
func (m *Migrations) GetStatementIndex() int64 { return m.StatementIndex }

// GetStatus will return the value of Status.
func (m *Migrations) GetStatus() string { return m.Status }

// MigrationsTable is the name of the table in the DB.
const MigrationsTable = "`migrations`"

// MigrationsFields is a list of all columns in the DB table.
var MigrationsFields = []string{"project", "filename", "statement_index", "status"}

// MigrationsPrimaryFields are the primary key fields in the DB table.
var MigrationsPrimaryFields = []string{"project"}

// Email generated for db table `email`.
type Email struct {
	// ID
	ID string `db:"id"`

	// Recipient
	Recipient string `db:"recipient"`

	// Subject
	Subject string `db:"subject"`

	// Body
	Body string `db:"body"`

	// Status
	Status string `db:"status"`

	// Created At
	CreatedAt *time.Time `db:"created_at"`

	// Sent At
	SentAt *time.Time `db:"sent_at"`

	// Error
	Error string `db:"error"`

	// Retry Count
	RetryCount int64 `db:"retry_count"`

	// Last Error
	LastError string `db:"last_error"`

	// Last Retry
	LastRetry *time.Time `db:"last_retry"`
}

// GetID will return the value of ID.
func (e *Email) GetID() string { return e.ID }

// GetRecipient will return the value of Recipient.
func (e *Email) GetRecipient() string { return e.Recipient }

// GetSubject will return the value of Subject.
func (e *Email) GetSubject() string { return e.Subject }

// GetBody will return the value of Body.
func (e *Email) GetBody() string { return e.Body }

// GetStatus will return the value of Status.
func (e *Email) GetStatus() string { return e.Status }

// GetCreatedAt will return the value of CreatedAt.
func (e *Email) GetCreatedAt() *time.Time { return e.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (e *Email) SetCreatedAt(stamp time.Time) { e.CreatedAt = &stamp }

// GetSentAt will return the value of SentAt.
func (e *Email) GetSentAt() *time.Time { return e.SentAt }

// SetSentAt sets SentAt to the provided value.
func (e *Email) SetSentAt(stamp time.Time) { e.SentAt = &stamp }

// GetError will return the value of Error.
func (e *Email) GetError() string { return e.Error }

// GetRetryCount will return the value of RetryCount.
func (e *Email) GetRetryCount() int64 { return e.RetryCount }

// GetLastError will return the value of LastError.
func (e *Email) GetLastError() string { return e.LastError }

// GetLastRetry will return the value of LastRetry.
func (e *Email) GetLastRetry() *time.Time { return e.LastRetry }

// SetLastRetry sets LastRetry to the provided value.
func (e *Email) SetLastRetry(stamp time.Time) { e.LastRetry = &stamp }

// EmailTable is the name of the table in the DB.
const EmailTable = "`email`"

// EmailFields is a list of all columns in the DB table.
var EmailFields = []string{"id", "recipient", "subject", "body", "status", "created_at", "sent_at", "error", "retry_count", "last_error", "last_retry"}

// EmailPrimaryFields are the primary key fields in the DB table.
var EmailPrimaryFields = []string{"id"}

// EmailSent generated for db table `email_sent`.
type EmailSent struct {
	// ID
	ID string `db:"id"`

	// Recipient
	Recipient string `db:"recipient"`

	// Subject
	Subject string `db:"subject"`

	// Body
	Body string `db:"body"`

	// Status
	Status string `db:"status"`

	// Created At
	CreatedAt *time.Time `db:"created_at"`

	// Sent At
	SentAt *time.Time `db:"sent_at"`

	// Error
	Error string `db:"error"`

	// Retry Count
	RetryCount int64 `db:"retry_count"`

	// Last Error
	LastError string `db:"last_error"`

	// Last Retry
	LastRetry *time.Time `db:"last_retry"`
}

// GetID will return the value of ID.
func (e *EmailSent) GetID() string { return e.ID }

// GetRecipient will return the value of Recipient.
func (e *EmailSent) GetRecipient() string { return e.Recipient }

// GetSubject will return the value of Subject.
func (e *EmailSent) GetSubject() string { return e.Subject }

// GetBody will return the value of Body.
func (e *EmailSent) GetBody() string { return e.Body }

// GetStatus will return the value of Status.
func (e *EmailSent) GetStatus() string { return e.Status }

// GetCreatedAt will return the value of CreatedAt.
func (e *EmailSent) GetCreatedAt() *time.Time { return e.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (e *EmailSent) SetCreatedAt(stamp time.Time) { e.CreatedAt = &stamp }

// GetSentAt will return the value of SentAt.
func (e *EmailSent) GetSentAt() *time.Time { return e.SentAt }

// SetSentAt sets SentAt to the provided value.
func (e *EmailSent) SetSentAt(stamp time.Time) { e.SentAt = &stamp }

// GetError will return the value of Error.
func (e *EmailSent) GetError() string { return e.Error }

// GetRetryCount will return the value of RetryCount.
func (e *EmailSent) GetRetryCount() int64 { return e.RetryCount }

// GetLastError will return the value of LastError.
func (e *EmailSent) GetLastError() string { return e.LastError }

// GetLastRetry will return the value of LastRetry.
func (e *EmailSent) GetLastRetry() *time.Time { return e.LastRetry }

// SetLastRetry sets LastRetry to the provided value.
func (e *EmailSent) SetLastRetry(stamp time.Time) { e.LastRetry = &stamp }

// EmailSentTable is the name of the table in the DB.
const EmailSentTable = "`email_sent`"

// EmailSentFields is a list of all columns in the DB table.
var EmailSentFields = []string{"id", "recipient", "subject", "body", "status", "created_at", "sent_at", "error", "retry_count", "last_error", "last_retry"}

// EmailSentPrimaryFields are the primary key fields in the DB table.
var EmailSentPrimaryFields = []string{"id"}

// EmailFailed generated for db table `email_failed`.
type EmailFailed struct {
	// ID
	ID string `db:"id"`

	// Recipient
	Recipient string `db:"recipient"`

	// Subject
	Subject string `db:"subject"`

	// Body
	Body string `db:"body"`

	// Status
	Status string `db:"status"`

	// Created At
	CreatedAt *time.Time `db:"created_at"`

	// Sent At
	SentAt *time.Time `db:"sent_at"`

	// Error
	Error string `db:"error"`

	// Retry Count
	RetryCount int64 `db:"retry_count"`

	// Last Error
	LastError string `db:"last_error"`

	// Last Retry
	LastRetry *time.Time `db:"last_retry"`
}

// GetID will return the value of ID.
func (e *EmailFailed) GetID() string { return e.ID }

// GetRecipient will return the value of Recipient.
func (e *EmailFailed) GetRecipient() string { return e.Recipient }

// GetSubject will return the value of Subject.
func (e *EmailFailed) GetSubject() string { return e.Subject }

// GetBody will return the value of Body.
func (e *EmailFailed) GetBody() string { return e.Body }

// GetStatus will return the value of Status.
func (e *EmailFailed) GetStatus() string { return e.Status }

// GetCreatedAt will return the value of CreatedAt.
func (e *EmailFailed) GetCreatedAt() *time.Time { return e.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (e *EmailFailed) SetCreatedAt(stamp time.Time) { e.CreatedAt = &stamp }

// GetSentAt will return the value of SentAt.
func (e *EmailFailed) GetSentAt() *time.Time { return e.SentAt }

// SetSentAt sets SentAt to the provided value.
func (e *EmailFailed) SetSentAt(stamp time.Time) { e.SentAt = &stamp }

// GetError will return the value of Error.
func (e *EmailFailed) GetError() string { return e.Error }

// GetRetryCount will return the value of RetryCount.
func (e *EmailFailed) GetRetryCount() int64 { return e.RetryCount }

// GetLastError will return the value of LastError.
func (e *EmailFailed) GetLastError() string { return e.LastError }

// GetLastRetry will return the value of LastRetry.
func (e *EmailFailed) GetLastRetry() *time.Time { return e.LastRetry }

// SetLastRetry sets LastRetry to the provided value.
func (e *EmailFailed) SetLastRetry(stamp time.Time) { e.LastRetry = &stamp }

// EmailFailedTable is the name of the table in the DB.
const EmailFailedTable = "`email_failed`"

// EmailFailedFields is a list of all columns in the DB table.
var EmailFailedFields = []string{"id", "recipient", "subject", "body", "status", "created_at", "sent_at", "error", "retry_count", "last_error", "last_retry"}

// EmailFailedPrimaryFields are the primary key fields in the DB table.
var EmailFailedPrimaryFields = []string{"id"}
