package model

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"fmt"
	"strings"
	"time"
)

// QueryOption is implemented by each data model type.
type QueryOption interface {
	WithTable(name string) QueryOption
	WithColumns(cols []string) QueryOption
	WithWhere(clause string) QueryOption
	WithOrderBy(clause string) QueryOption
	WithLimit(start, offset int) QueryOption
	WithStatement(stmt string) QueryOption
}

// QueryConfig is a function-chaining SQL statement type.
type QueryConfig struct {
	Table       string
	Columns     []string
	Where       string
	OrderBy     string
	LimitStart  int
	LimitOffset int
	Statement   string
}

// WithTable will set the table name for the query.
func (q *QueryConfig) WithTable(name string) QueryOption {
	q.Table = name
	return q
}

// WithColumns will set the columns to use for the query.
func (q *QueryConfig) WithColumns(cols []string) QueryOption {
	q.Columns = cols
	return q
}

// WithWhere will set the where condition for the query.
func (q *QueryConfig) WithWhere(clause string) QueryOption {
	q.Where = clause
	return q
}

// WithOrderBy will set the order by clause for the query.
func (q *QueryConfig) WithOrderBy(clause string) QueryOption {
	q.OrderBy = clause
	return q
}

// WithLimit will set the limit clause parameters for the query.
func (q *QueryConfig) WithLimit(start, offset int) QueryOption {
	q.LimitStart = start
	q.LimitOffset = offset
	return q
}

// WithStatement will change the statement for the query.
func (q *QueryConfig) WithStatement(stmt string) QueryOption {
	q.Statement = stmt
	return q
}

// WithTable will set the table name for the query.
func WithTable(name string) QueryOption {
	return &QueryConfig{Table: name}
}

// WithColumns will set the columns to use for the query.
func WithColumns(cols []string) QueryOption {
	return &QueryConfig{Columns: cols}
}

// WithWhere will set the where condition for the query.
func WithWhere(clause string) QueryOption {
	return &QueryConfig{Where: clause}
}

// WithOrderBy will set the order by clause for the query.
func WithOrderBy(clause string) QueryOption {
	return &QueryConfig{OrderBy: clause}
}

// WithLimit will set the limit clause parameters for the query.
func WithLimit(start, offset int) QueryOption {
	return &QueryConfig{LimitStart: start, LimitOffset: offset}
}

// WithStatement will change the statement for the query.
func WithStatement(stmt string) QueryOption {
	return &QueryConfig{Statement: stmt}
}

// Apply will use passed query options to populate the query.
func (q *QueryConfig) Apply(opts ...QueryOption) *QueryConfig {
	cfg := *q
	for _, opt := range opts {
		o := opt.(*QueryConfig)
		if o.Table != "" {
			cfg.Table = o.Table
		}
		if len(o.Columns) > 0 {
			cfg.Columns = o.Columns
		}
		if o.Where != "" {
			cfg.Where = o.Where
		}
		if o.OrderBy != "" {
			cfg.OrderBy = o.OrderBy
		}
		if o.LimitOffset > 0 {
			cfg.LimitStart = o.LimitStart
			cfg.LimitOffset = o.LimitOffset
		}
		if o.Statement != "" {
			cfg.Statement = o.Statement
		}
	}
	return &cfg
}

// Article generated for db table `article`.
type Article struct {
	// ID
	ID string `db:"id" json:"id"`

	// Slug
	Slug string `db:"slug" json:"slug"`

	// Title
	Title string `db:"title" json:"title"`

	// Filename
	Filename string `db:"filename" json:"filename"`

	// Description
	Description string `db:"description" json:"description"`

	// Date
	Date *time.Time `db:"date" json:"date"`

	// Og Image
	OgImage string `db:"og_image" json:"og_image"`

	// Layout
	Layout string `db:"layout" json:"layout"`

	// Source
	Source string `db:"source" json:"source"`

	// URL
	URL string `db:"url" json:"url"`

	// Draft
	Draft int64 `db:"draft" json:"draft"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

// GetID will return the value of ID.
func (a *Article) GetID() string { return a.ID }

// GetSlug will return the value of Slug.
func (a *Article) GetSlug() string { return a.Slug }

// GetTitle will return the value of Title.
func (a *Article) GetTitle() string { return a.Title }

// GetFilename will return the value of Filename.
func (a *Article) GetFilename() string { return a.Filename }

// GetDescription will return the value of Description.
func (a *Article) GetDescription() string { return a.Description }

// GetDate will return the value of Date.
func (a *Article) GetDate() *time.Time { return a.Date }

// SetDate sets Date to the provided value.
func (a *Article) SetDate(stamp time.Time) { a.Date = &stamp }

// GetOgImage will return the value of OgImage.
func (a *Article) GetOgImage() string { return a.OgImage }

// GetLayout will return the value of Layout.
func (a *Article) GetLayout() string { return a.Layout }

// GetSource will return the value of Source.
func (a *Article) GetSource() string { return a.Source }

// GetURL will return the value of URL.
func (a *Article) GetURL() string { return a.URL }

// GetDraft will return the value of Draft.
func (a *Article) GetDraft() int64 { return a.Draft }

// GetCreatedAt will return the value of CreatedAt.
func (a *Article) GetCreatedAt() *time.Time { return a.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (a *Article) SetCreatedAt(stamp time.Time) { a.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (a *Article) GetUpdatedAt() *time.Time { return a.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (a *Article) SetUpdatedAt(stamp time.Time) { a.UpdatedAt = &stamp }

// ArticleTable is the name of the table in the DB.
const ArticleTable = "`article`"

// ArticleFields is a list of all columns in the DB table.
var ArticleFields = []string{"id", "slug", "title", "filename", "description", "date", "og_image", "layout", "source", "url", "draft", "created_at", "updated_at"}

// ArticlePrimaryFields are the primary key fields in the DB table.
var ArticlePrimaryFields = []string{"id"}

// Migrations generated for db table `migrations`.
type Migrations struct {
	// Project
	Project string `db:"project" json:"project"`

	// Filename
	Filename string `db:"filename" json:"filename"`

	// Statement Index
	StatementIndex int64 `db:"statement_index" json:"statement_index"`

	// Status
	Status string `db:"status" json:"status"`
}

// GetProject will return the value of Project.
func (m *Migrations) GetProject() string { return m.Project }

// GetFilename will return the value of Filename.
func (m *Migrations) GetFilename() string { return m.Filename }

// GetStatementIndex will return the value of StatementIndex.
func (m *Migrations) GetStatementIndex() int64 { return m.StatementIndex }

// GetStatus will return the value of Status.
func (m *Migrations) GetStatus() string { return m.Status }

// MigrationsTable is the name of the table in the DB.
const MigrationsTable = "`migrations`"

// MigrationsFields is a list of all columns in the DB table.
var MigrationsFields = []string{"project", "filename", "statement_index", "status"}

// MigrationsPrimaryFields are the primary key fields in the DB table.
var MigrationsPrimaryFields = []string{"project", "filename"}

// Setting generated for db table `setting`.
type Setting struct {
	// User ID
	UserID string `db:"user_id" json:"user_id"`

	// Meta Lang
	MetaLang string `db:"meta_lang" json:"meta_lang"`

	// Meta URL
	MetaURL string `db:"meta_url" json:"meta_url"`

	// Meta Author Name
	MetaAuthorName string `db:"meta_author_name" json:"meta_author_name"`

	// Meta Subtitle
	MetaSubtitle string `db:"meta_subtitle" json:"meta_subtitle"`

	// Meta Headshot
	MetaHeadshot string `db:"meta_headshot" json:"meta_headshot"`

	// Posts Per Page
	PostsPerPage int64 `db:"posts_per_page" json:"posts_per_page"`

	// Social Github
	SocialGithub string `db:"social_github" json:"social_github"`

	// Social Twitter
	SocialTwitter string `db:"social_twitter" json:"social_twitter"`

	// Social Linkedin
	SocialLinkedin string `db:"social_linkedin" json:"social_linkedin"`

	// Feature Webmention
	FeatureWebmention int64 `db:"feature_webmention" json:"feature_webmention"`

	// Feature Pingback
	FeaturePingback int64 `db:"feature_pingback" json:"feature_pingback"`

	// Feature Comments
	FeatureComments int64 `db:"feature_comments" json:"feature_comments"`

	// Feature Rss
	FeatureRss int64 `db:"feature_rss" json:"feature_rss"`

	// Seo Title Suffix
	SeoTitleSuffix string `db:"seo_title_suffix" json:"seo_title_suffix"`

	// Seo Default Image
	SeoDefaultImage string `db:"seo_default_image" json:"seo_default_image"`

	// Analytics ID
	AnalyticsID string `db:"analytics_id" json:"analytics_id"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

// GetUserID will return the value of UserID.
func (s *Setting) GetUserID() string { return s.UserID }

// GetMetaLang will return the value of MetaLang.
func (s *Setting) GetMetaLang() string { return s.MetaLang }

// GetMetaURL will return the value of MetaURL.
func (s *Setting) GetMetaURL() string { return s.MetaURL }

// GetMetaAuthorName will return the value of MetaAuthorName.
func (s *Setting) GetMetaAuthorName() string { return s.MetaAuthorName }

// GetMetaSubtitle will return the value of MetaSubtitle.
func (s *Setting) GetMetaSubtitle() string { return s.MetaSubtitle }

// GetMetaHeadshot will return the value of MetaHeadshot.
func (s *Setting) GetMetaHeadshot() string { return s.MetaHeadshot }

// GetPostsPerPage will return the value of PostsPerPage.
func (s *Setting) GetPostsPerPage() int64 { return s.PostsPerPage }

// GetSocialGithub will return the value of SocialGithub.
func (s *Setting) GetSocialGithub() string { return s.SocialGithub }

// GetSocialTwitter will return the value of SocialTwitter.
func (s *Setting) GetSocialTwitter() string { return s.SocialTwitter }

// GetSocialLinkedin will return the value of SocialLinkedin.
func (s *Setting) GetSocialLinkedin() string { return s.SocialLinkedin }

// GetFeatureWebmention will return the value of FeatureWebmention.
func (s *Setting) GetFeatureWebmention() int64 { return s.FeatureWebmention }

// GetFeaturePingback will return the value of FeaturePingback.
func (s *Setting) GetFeaturePingback() int64 { return s.FeaturePingback }

// GetFeatureComments will return the value of FeatureComments.
func (s *Setting) GetFeatureComments() int64 { return s.FeatureComments }

// GetFeatureRss will return the value of FeatureRss.
func (s *Setting) GetFeatureRss() int64 { return s.FeatureRss }

// GetSeoTitleSuffix will return the value of SeoTitleSuffix.
func (s *Setting) GetSeoTitleSuffix() string { return s.SeoTitleSuffix }

// GetSeoDefaultImage will return the value of SeoDefaultImage.
func (s *Setting) GetSeoDefaultImage() string { return s.SeoDefaultImage }

// GetAnalyticsID will return the value of AnalyticsID.
func (s *Setting) GetAnalyticsID() string { return s.AnalyticsID }

// GetCreatedAt will return the value of CreatedAt.
func (s *Setting) GetCreatedAt() *time.Time { return s.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (s *Setting) SetCreatedAt(stamp time.Time) { s.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (s *Setting) GetUpdatedAt() *time.Time { return s.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (s *Setting) SetUpdatedAt(stamp time.Time) { s.UpdatedAt = &stamp }

// SettingTable is the name of the table in the DB.
const SettingTable = "`setting`"

// SettingFields is a list of all columns in the DB table.
var SettingFields = []string{"user_id", "meta_lang", "meta_url", "meta_author_name", "meta_subtitle", "meta_headshot", "posts_per_page", "social_github", "social_twitter", "social_linkedin", "feature_webmention", "feature_pingback", "feature_comments", "feature_rss", "seo_title_suffix", "seo_default_image", "analytics_id", "created_at", "updated_at"}

// SettingPrimaryFields are the primary key fields in the DB table.
var SettingPrimaryFields = []string{"user_id"}

// Insert starts building an INSERT INTO query.
func (a *Article) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: ArticleTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := ArticleFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (a *Article) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: ArticleTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (a *Article) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: ArticleTable}).Apply(opts...)
	cols := ArticleFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (a *Article) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: ArticleTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (m *Migrations) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (m *Migrations) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (m *Migrations) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (m *Migrations) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (s *Setting) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SettingTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := SettingFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (s *Setting) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SettingTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (s *Setting) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SettingTable}).Apply(opts...)
	cols := SettingFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (s *Setting) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SettingTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}
