@startuml
[github.com/titpetric/platform-app/autoload] --|> [github.com/titpetric/platform-app/cmd]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/modules/assets]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/modules/daily]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/modules/email]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/modules/expvar]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/modules/user]
[github.com/titpetric/platform-app/cmd/app] --|> [github.com/titpetric/platform-app/cmd]
[github.com/titpetric/platform-app/modules/daily] --|> [github.com/titpetric/platform-app/modules/daily/model]
[github.com/titpetric/platform-app/modules/daily] --|> [github.com/titpetric/platform-app/modules/daily/storage]
[github.com/titpetric/platform-app/modules/daily] --|> [github.com/titpetric/platform-app/modules/daily/view]
[github.com/titpetric/platform-app/modules/daily] --|> [github.com/titpetric/platform-app/modules/user]
[github.com/titpetric/platform-app/modules/daily/storage] --|> [github.com/titpetric/platform-app/modules/daily/model]
[github.com/titpetric/platform-app/modules/daily/storage] --|> [github.com/titpetric/platform-app/modules/user]
[github.com/titpetric/platform-app/modules/daily/view] --|> [github.com/titpetric/platform-app/modules/daily/model]
[github.com/titpetric/platform-app/modules/daily/view] --|> [github.com/titpetric/platform-app/modules/theme]
[github.com/titpetric/platform-app/modules/daily/view] --|> [github.com/titpetric/platform-app/modules/user/model]
[github.com/titpetric/platform-app/modules/email] --|> [github.com/titpetric/platform-app/modules/email/model]
[github.com/titpetric/platform-app/modules/email] --|> [github.com/titpetric/platform-app/modules/email/smtp]
[github.com/titpetric/platform-app/modules/email] --|> [github.com/titpetric/platform-app/modules/email/storage]
[github.com/titpetric/platform-app/modules/email/storage] --|> [github.com/titpetric/platform-app/modules/email/model]
[github.com/titpetric/platform-app/modules/user] --|> [github.com/titpetric/platform-app/modules/user/model]
[github.com/titpetric/platform-app/modules/user] --|> [github.com/titpetric/platform-app/modules/user/service]
[github.com/titpetric/platform-app/modules/user] --|> [github.com/titpetric/platform-app/modules/user/storage]
[github.com/titpetric/platform-app/modules/user/service] --|> [github.com/titpetric/platform-app/modules/user/model]
[github.com/titpetric/platform-app/modules/user/service] --|> [github.com/titpetric/platform-app/modules/user/storage]
[github.com/titpetric/platform-app/modules/user/service] --|> [github.com/titpetric/platform-app/modules/user/view]
[github.com/titpetric/platform-app/modules/user/storage] --|> [github.com/titpetric/platform-app/modules/user/model]
[github.com/titpetric/platform-app/modules/user/view] --|> [github.com/titpetric/platform-app/modules/theme]
[github.com/titpetric/platform-app/modules/user/view] --|> [github.com/titpetric/platform-app/modules/user/model]
@enduml
