@startuml
[modules.daily.storage] --|> [modules.user.model]
[modules.daily.view] --|> [modules.user.model]
[modules.daily.view] --|> [modules.theme]
[modules.daily] --|> [modules.user.storage]
[modules.daily] --|> [modules.user.model]
[modules.daily] --|> [modules.user.view]
[modules.user.storage] --|> [modules.user.model]
[modules.user.view] --|> [modules.theme]
[modules.user.view] --|> [modules.user.model]
[modules.user.service] --|> [modules.user.storage]
[modules.user.service] --|> [modules.user.model]
[modules.user.service] --|> [modules.user.view]
[modules.user] --|> [modules.user.service]
[modules.user] --|> [modules.user.storage]
[modules.user] --|> [modules.user.model]
[cmd] --|> [modules.expvar]
[cmd] --|> [modules.user]
[cmd] --|> [modules.assets]
[cmd] --|> [modules.daily]
[autoload] --|> [cmd]
[cmd.app] --|> [cmd]
@enduml
