@startuml
[github.com/titpetric/platform-app/autoload] --|> [github.com/titpetric/platform-app/cmd]
[github.com/titpetric/platform-app/blog] --|> [github.com/titpetric/platform-app/blog/handlers]
[github.com/titpetric/platform-app/blog] --|> [github.com/titpetric/platform-app/blog/markdown]
[github.com/titpetric/platform-app/blog] --|> [github.com/titpetric/platform-app/blog/model]
[github.com/titpetric/platform-app/blog] --|> [github.com/titpetric/platform-app/blog/storage]
[github.com/titpetric/platform-app/blog] --|> [github.com/titpetric/platform-app/blog/view]
[github.com/titpetric/platform-app/blog/cmd/blog] --|> [github.com/titpetric/platform-app/blog]
[github.com/titpetric/platform-app/blog/cmd/blog] --|> [github.com/titpetric/platform-app/user]
[github.com/titpetric/platform-app/blog/cmd/generate] --|> [github.com/titpetric/platform-app/blog]
[github.com/titpetric/platform-app/blog/cmd/generate] --|> [github.com/titpetric/platform-app/blog/storage]
[github.com/titpetric/platform-app/blog/handlers] --|> [github.com/titpetric/platform-app/blog/markdown]
[github.com/titpetric/platform-app/blog/handlers] --|> [github.com/titpetric/platform-app/blog/model]
[github.com/titpetric/platform-app/blog/handlers] --|> [github.com/titpetric/platform-app/blog/storage]
[github.com/titpetric/platform-app/blog/handlers] --|> [github.com/titpetric/platform-app/blog/view]
[github.com/titpetric/platform-app/blog/storage] --|> [github.com/titpetric/platform-app/blog/model]
[github.com/titpetric/platform-app/blog/storage] --|> [github.com/titpetric/platform-app/blog/schema]
[github.com/titpetric/platform-app/blog/view] --|> [github.com/titpetric/platform-app/blog/model]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/blog]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/daily]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/email]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/expvar]
[github.com/titpetric/platform-app/cmd] --|> [github.com/titpetric/platform-app/user]
[github.com/titpetric/platform-app/cmd/app] --|> [github.com/titpetric/platform-app/cmd]
[github.com/titpetric/platform-app/daily] --|> [github.com/titpetric/platform-app/daily/model]
[github.com/titpetric/platform-app/daily] --|> [github.com/titpetric/platform-app/daily/schema]
[github.com/titpetric/platform-app/daily] --|> [github.com/titpetric/platform-app/daily/storage]
[github.com/titpetric/platform-app/daily] --|> [github.com/titpetric/platform-app/daily/view]
[github.com/titpetric/platform-app/daily] --|> [github.com/titpetric/platform-app/user]
[github.com/titpetric/platform-app/daily/model] --|> [github.com/titpetric/platform-app/user/model]
[github.com/titpetric/platform-app/daily/storage] --|> [github.com/titpetric/platform-app/daily/model]
[github.com/titpetric/platform-app/daily/storage] --|> [github.com/titpetric/platform-app/daily/schema]
[github.com/titpetric/platform-app/daily/storage] --|> [github.com/titpetric/platform-app/user]
[github.com/titpetric/platform-app/daily/view] --|> [github.com/titpetric/platform-app/daily/model]
[github.com/titpetric/platform-app/email] --|> [github.com/titpetric/platform-app/email/model]
[github.com/titpetric/platform-app/email] --|> [github.com/titpetric/platform-app/email/schema]
[github.com/titpetric/platform-app/email] --|> [github.com/titpetric/platform-app/email/smtp]
[github.com/titpetric/platform-app/email] --|> [github.com/titpetric/platform-app/email/storage]
[github.com/titpetric/platform-app/email/storage] --|> [github.com/titpetric/platform-app/email/model]
[github.com/titpetric/platform-app/maillist] --|> [github.com/titpetric/platform-app/maillist/storage]
[github.com/titpetric/platform-app/maillist/storage] --|> [github.com/titpetric/platform-app/user]
[github.com/titpetric/platform-app/maillist/storage] --|> [github.com/titpetric/platform-app/user/model]
[github.com/titpetric/platform-app/pulse] --|> [github.com/titpetric/platform-app/pulse/service]
[github.com/titpetric/platform-app/pulse/cmd/pulse] --|> [github.com/titpetric/platform-app/pulse]
[github.com/titpetric/platform-app/pulse/cmd/pulse] --|> [github.com/titpetric/platform-app/user]
[github.com/titpetric/platform-app/pulse/service] --|> [github.com/titpetric/platform-app/pulse/storage]
[github.com/titpetric/platform-app/pulse/storage] --|> [github.com/titpetric/platform-app/user]
[github.com/titpetric/platform-app/user] --|> [github.com/titpetric/platform-app/user/model]
[github.com/titpetric/platform-app/user] --|> [github.com/titpetric/platform-app/user/service]
[github.com/titpetric/platform-app/user] --|> [github.com/titpetric/platform-app/user/storage]
[github.com/titpetric/platform-app/user/service] --|> [github.com/titpetric/platform-app/user/model]
[github.com/titpetric/platform-app/user/service] --|> [github.com/titpetric/platform-app/user/storage]
[github.com/titpetric/platform-app/user/service] --|> [github.com/titpetric/platform-app/user/view]
[github.com/titpetric/platform-app/user/storage] --|> [github.com/titpetric/platform-app/user/model]
[github.com/titpetric/platform-app/user/view] --|> [github.com/titpetric/platform-app/user/model]
@enduml
