@startuml

class "blog.markdown.Renderer" {
  - codeBlockPattern: *regexp.Regexp
  + Render (content []byte) []byte
}

class "blog.model.Article" {
  + ID: string
  + Slug: string
  + Title: string
  + Filename: string
  + Description: string
  + Date: *time.Time
  + OgImage: string
  + Layout: string
  + Source: string
  + URL: string
  + CreatedAt: *time.Time
  + UpdatedAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetCreatedAt () *time.Time
  + GetDate () *time.Time
  + GetDescription () string
  + GetFilename () string
  + GetID () string
  + GetLayout () string
  + GetOgImage () string
  + GetSlug () string
  + GetSource () string
  + GetTitle () string
  + GetURL () string
  + GetUpdatedAt () *time.Time
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetDate (stamp time.Time)
  + SetUpdatedAt (stamp time.Time)
  + Update (opts ...QueryOption) string
}

class "blog.model.ArticleList" {
  + Articles: []Article
  + Total: int
  + Page: int
  + PageSize: int
}

class "blog.model.Metadata" {
  + Title: string
  + Description: string
  + OgImage: string
  + Date: string
  + Layout: string
  + Source: string
}

class "blog.model.Migrations" {
  + Project: string
  + Filename: string
  + StatementIndex: int64
  + Status: string
  + Delete (opts ...QueryOption) string
  + GetFilename () string
  + GetProject () string
  + GetStatementIndex () int64
  + GetStatus () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + Update (opts ...QueryOption) string
}

class "blog.model.QueryConfig" {
  + Table: string
  + Columns: []string
  + Where: string
  + OrderBy: string
  + LimitStart: int
  + LimitOffset: int
  + Statement: string
  + Apply (opts ...QueryOption) *QueryConfig
  + WithColumns (cols []string) QueryOption
  + WithLimit (start,offset int) QueryOption
  + WithOrderBy (clause string) QueryOption
  + WithStatement (stmt string) QueryOption
  + WithTable (name string) QueryOption
  + WithWhere (clause string) QueryOption
}

interface "blog.model.QueryOption" {
  + WithTable: WithTable (name string) QueryOption
  + WithColumns: WithColumns (cols []string) QueryOption
  + WithWhere: WithWhere (clause string) QueryOption
  + WithOrderBy: WithOrderBy (clause string) QueryOption
  + WithLimit: WithLimit (start,offset int) QueryOption
  + WithStatement: WithStatement (stmt string) QueryOption
}

class "blog.storage.Storage" {
  - db: *sqlx.DB
  + CountArticles (ctx context.Context) (int, error)
  + GetArticleBySlug (ctx context.Context, slug string) (*model.Article, error)
  + GetArticles (ctx context.Context, start,length int) ([]model.Article, error)
  + InsertArticle (ctx context.Context, article *model.Article) error
  + SearchArticles (ctx context.Context, query string) ([]model.Article, error)
}

class "blog.view.IndexData" {
  + Articles: []model.Article
  + Data: map[string]any
  + Total: int
  + Fill ()
  + Map () map[string]any
}

class "blog.view.Loader" {
  - tpl: vuego.Template
  + Load (filename string) vuego.Template
}

class "blog.view.PostData" {
  + Slug: string
  + Title: string
  + Description: string
  + OgImage: string
  + Content: string
  + Date: *time.Time
  + Class: string
  + Map () map[string]any
}

class "blog.view.Views" {
  + Loader: *Loader
  + AtomFeed (ctx context.Context, w io.Writer, articles []model.Article, meta map[string]any) error
  + Blog (data *IndexData) vuego.Template
  + Index (data *IndexData) vuego.Template
  + Post (data *PostData) vuego.Template
}

class "blog.handlers.Handlers" {
  - repository: *storage.Storage
  - views: *view.Views
  + GetArticleAdminJSON (w http.ResponseWriter, r *http.Request)
  + GetArticleHTML (w http.ResponseWriter, r *http.Request)
  + GetArticleJSON (w http.ResponseWriter, r *http.Request)
  + GetAtomFeed (w http.ResponseWriter, r *http.Request)
  + IndexHTML (w http.ResponseWriter, r *http.Request)
  + ListArticlesAdminHTML (w http.ResponseWriter, r *http.Request)
  + ListArticlesAdminJSON (w http.ResponseWriter, r *http.Request)
  + ListArticlesHTML (w http.ResponseWriter, r *http.Request)
  + ListArticlesJSON (w http.ResponseWriter, r *http.Request)
  + Repository () *storage.Storage
  + SearchArticlesJSON (w http.ResponseWriter, r *http.Request)
  + Views () *view.Views
}

class "blog.Generator" {
  - module: *Module
  - outputDir: string
  + Generate (ctx context.Context) error
}

class "blog.Module" {
  - dataDir: string
  - repository: *storage.Storage
  - articles: map[string]*model.Article
  - themeFS: fs.FS
  + Mount (_ context.Context, r platform.Router) error
  + Name () string
  + ScanMarkdownFiles (ctx context.Context) (int, error)
  + SetRepository (repo *storage.Storage)
  + Start (ctx context.Context) error
  + Stop (context.Context) error
}

class "user.model.QueryConfig" {
  + Table: string
  + Columns: []string
  + Where: string
  + OrderBy: string
  + LimitStart: int
  + LimitOffset: int
  + Statement: string
  + Apply (opts ...QueryOption) *QueryConfig
  + WithColumns (cols []string) QueryOption
  + WithLimit (start,offset int) QueryOption
  + WithOrderBy (clause string) QueryOption
  + WithStatement (stmt string) QueryOption
  + WithTable (name string) QueryOption
  + WithWhere (clause string) QueryOption
}

interface "user.model.QueryOption" {
  + WithTable: WithTable (name string) QueryOption
  + WithColumns: WithColumns (cols []string) QueryOption
  + WithWhere: WithWhere (clause string) QueryOption
  + WithOrderBy: WithOrderBy (clause string) QueryOption
  + WithLimit: WithLimit (start,offset int) QueryOption
  + WithStatement: WithStatement (stmt string) QueryOption
}

interface "user.model.SessionStorage" {
  + Create: Create (ctx context.Context, userID string) (*UserSession, error)
  + Get: Get (ctx context.Context, sessionID string) (*UserSession, error)
  + Delete: Delete (ctx context.Context, sessionID string) error
}

class "user.model.User" {
  + ID: string
  + FirstName: string
  + LastName: string
  + DeletedAt: *time.Time
  + CreatedAt: *time.Time
  + UpdatedAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetCreatedAt () *time.Time
  + GetDeletedAt () *time.Time
  + GetFirstName () string
  + GetID () string
  + GetLastName () string
  + GetUpdatedAt () *time.Time
  + Insert (opts ...QueryOption) string
  + IsActive () bool
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetDeletedAt (stamp time.Time)
  + SetUpdatedAt (stamp time.Time)
  + String () string
  + Update (opts ...QueryOption) string
}

class "user.model.UserAuth" {
  + UserID: string
  + Email: string
  + Password: string
  + CreatedAt: *time.Time
  + UpdatedAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetCreatedAt () *time.Time
  + GetEmail () string
  + GetPassword () string
  + GetUpdatedAt () *time.Time
  + GetUserID () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetUpdatedAt (stamp time.Time)
  + Update (opts ...QueryOption) string
  + Valid () bool
}

class "user.model.UserGroup" {
  + ID: string
  + Title: string
  + CreatedAt: *time.Time
  + UpdatedAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetCreatedAt () *time.Time
  + GetID () string
  + GetTitle () string
  + GetUpdatedAt () *time.Time
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetUpdatedAt (stamp time.Time)
  + String () string
  + Update (opts ...QueryOption) string
}

class "user.model.UserGroupMember" {
  + UserGroupID: string
  + UserID: string
  + JoinedAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetJoinedAt () *time.Time
  + GetUserGroupID () string
  + GetUserID () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetJoinedAt (stamp time.Time)
  + Update (opts ...QueryOption) string
}

class "user.model.UserSession" {
  + ID: string
  + UserID: string
  + ExpiresAt: *time.Time
  + CreatedAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetCreatedAt () *time.Time
  + GetExpiresAt () *time.Time
  + GetID () string
  + GetUserID () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetExpiresAt (stamp time.Time)
  + Update (opts ...QueryOption) string
}

interface "user.model.UserStorage" {
  + Create: Create (context.Context, *User, *UserAuth) (*User, error)
  + Update: Update (context.Context, *User) (*User, error)
  + Get: Get (context.Context, string) (*User, error)
  + GetGroups: GetGroups (context.Context, string) ([]UserGroup, error)
  + Authenticate: Authenticate (ctx context.Context, auth UserAuth) (*User, error)
}

class "daily.model.Migrations" {
  + Project: string
  + Filename: string
  + StatementIndex: int64
  + Status: string
  + Delete (opts ...QueryOption) string
  + GetFilename () string
  + GetProject () string
  + GetStatementIndex () int64
  + GetStatus () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + Update (opts ...QueryOption) string
}

class "daily.model.QueryConfig" {
  + Table: string
  + Columns: []string
  + Where: string
  + OrderBy: string
  + LimitStart: int
  + LimitOffset: int
  + Statement: string
  + Apply (opts ...QueryOption) *QueryConfig
  + WithColumns (cols []string) QueryOption
  + WithLimit (start,offset int) QueryOption
  + WithOrderBy (clause string) QueryOption
  + WithStatement (stmt string) QueryOption
  + WithTable (name string) QueryOption
  + WithWhere (clause string) QueryOption
}

interface "daily.model.QueryOption" {
  + WithTable: WithTable (name string) QueryOption
  + WithColumns: WithColumns (cols []string) QueryOption
  + WithWhere: WithWhere (clause string) QueryOption
  + WithOrderBy: WithOrderBy (clause string) QueryOption
  + WithLimit: WithLimit (start,offset int) QueryOption
  + WithStatement: WithStatement (stmt string) QueryOption
}

interface "daily.model.Storage" {
  + List: List (ctx context.Context) ([]Todo, error)
  + Get: Get (ctx context.Context, id string) (Todo, error)
  + Add: Add (ctx context.Context, t Todo) (Todo, error)
  + Update: Update (ctx context.Context, t Todo) error
  + Complete: Complete (ctx context.Context, id string) error
  + Delete: Delete (ctx context.Context, id string) error
}

class "daily.model.Todo" {
  + ID: string
  + UserID: string
  + Title: string
  + Completed: bool
  + CreatedAt: *time.Time
  + UpdatedAt: *time.Time
  + DeletedAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetCompleted () bool
  + GetCreatedAt () *time.Time
  + GetDeletedAt () *time.Time
  + GetID () string
  + GetTitle () string
  + GetUpdatedAt () *time.Time
  + GetUserID () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetDeletedAt (stamp time.Time)
  + SetUpdatedAt (stamp time.Time)
  + Update (opts ...QueryOption) string
}

class "daily.model.User" {
  - type: model.User
}

class "user.storage.SessionStorage" {
  - db: *sqlx.DB
  + Create (ctx context.Context, userID string) (*model.UserSession, error)
  + Delete (ctx context.Context, sessionID string) error
  + Get (ctx context.Context, sessionID string) (*model.UserSession, error)
}

class "user.storage.UserStorage" {
  - db: *sqlx.DB
  + Authenticate (ctx context.Context, userAuth model.UserAuth) (*model.User, error)
  + Create (ctx context.Context, u *model.User, userAuth *model.UserAuth) (*model.User, error)
  + Get (ctx context.Context, id string) (*model.User, error)
  + GetGroups (ctx context.Context, userID string) ([]model.UserGroup, error)
  + Update (ctx context.Context, u *model.User) (*model.User, error)
}

class "user.view.Renderer" {
  - root: fs.FS
  - tpl: vuego.Template
  - data: map[string]any
  + Load (filename string, data any) vuego.Template
  + Login (data LoginData) vuego.Template
  + Logout (data LogoutData) vuego.Template
  + Register (data RegisterData) vuego.Template
}

class "user.view.Data" {
  + SessionUser: *model.User
  + User: string
  + Email: string
  + ErrorMessage: string
  + FirstName: string
  + LastName: string
class "user.view.LoginData" {
  + SessionUser: *model.User
  + User: string
  + Email: string
  + ErrorMessage: string
  + FirstName: string
  + LastName: string
class "user.view.LogoutData" {
  + SessionUser: *model.User
  + User: string
  + Email: string
  + ErrorMessage: string
  + FirstName: string
  + LastName: string
class "user.view.RegisterData" {
  + SessionUser: *model.User
  + User: string
  + Email: string
  + ErrorMessage: string
  + FirstName: string
  + LastName: string
}

class "user.service.Service" {
  + UserStorage: *storage.UserStorage
  + SessionStorage: *storage.SessionStorage
  - view: *view.Renderer
  + Error (r *http.Request, message string, err error)
  + GetError (r *http.Request) string
  + Login (w http.ResponseWriter, r *http.Request)
  + LoginView (w http.ResponseWriter, r *http.Request)
  + Logout (w http.ResponseWriter, r *http.Request)
  + LogoutView (w http.ResponseWriter, r *http.Request)
  + Register (w http.ResponseWriter, r *http.Request)
  + RegisterView (w http.ResponseWriter, r *http.Request)
}

class "user.Handler" {
  + Mount (_ context.Context, r platform.Router) error
  + Name () string
  + Start (ctx context.Context) error
}

class "daily.storage.Storage" {
  - db: *sqlx.DB
  + Add (ctx context.Context, t model.Todo) (model.Todo, error)
  + Complete (ctx context.Context, id string) error
  + Delete (ctx context.Context, id string) error
  + Get (ctx context.Context, id string) (model.Todo, error)
  + List (ctx context.Context) ([]model.Todo, error)
  + Update (ctx context.Context, t model.Todo) error
}

class "daily.view.Data" {
  + Tasks: []model.Todo
  + SessionUser: *model.User
}

class "daily.view.Loader" {
  - tpl: vuego.Template
  + Load (filename string) vuego.Template
}

class "daily.view.Views" {
  + Loader: *Loader
  + Index (data Data) vuego.Template
}

class "daily.Module" {
  - repository: *storage.Storage
  - views: *view.Views
  + Mount (_ context.Context, r platform.Router) error
  + Name () string
  + Start (ctx context.Context) error
}

class "email.model.Email" {
  + ID: string
  + Recipient: string
  + Subject: string
  + Body: string
  + Status: string
  + Error: string
  + CreatedAt: *time.Time
  + SentAt: *time.Time
  + RetryCount: int64
  + RetryError: string
  + RetryAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetBody () string
  + GetCreatedAt () *time.Time
  + GetError () string
  + GetID () string
  + GetRecipient () string
  + GetRetryAt () *time.Time
  + GetRetryCount () int64
  + GetRetryError () string
  + GetSentAt () *time.Time
  + GetStatus () string
  + GetSubject () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetRetryAt (stamp time.Time)
  + SetSentAt (stamp time.Time)
  + Update (opts ...QueryOption) string
}

class "email.model.EmailFailed" {
  + ID: string
  + Recipient: string
  + Subject: string
  + Body: string
  + Status: string
  + Error: string
  + CreatedAt: *time.Time
  + SentAt: *time.Time
  + RetryCount: int64
  + RetryError: string
  + RetryAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetBody () string
  + GetCreatedAt () *time.Time
  + GetError () string
  + GetID () string
  + GetRecipient () string
  + GetRetryAt () *time.Time
  + GetRetryCount () int64
  + GetRetryError () string
  + GetSentAt () *time.Time
  + GetStatus () string
  + GetSubject () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetRetryAt (stamp time.Time)
  + SetSentAt (stamp time.Time)
  + Update (opts ...QueryOption) string
}

class "email.model.EmailSent" {
  + ID: string
  + Recipient: string
  + Subject: string
  + Body: string
  + Status: string
  + Error: string
  + CreatedAt: *time.Time
  + SentAt: *time.Time
  + RetryCount: int64
  + RetryError: string
  + RetryAt: *time.Time
  + Delete (opts ...QueryOption) string
  + GetBody () string
  + GetCreatedAt () *time.Time
  + GetError () string
  + GetID () string
  + GetRecipient () string
  + GetRetryAt () *time.Time
  + GetRetryCount () int64
  + GetRetryError () string
  + GetSentAt () *time.Time
  + GetStatus () string
  + GetSubject () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetCreatedAt (stamp time.Time)
  + SetRetryAt (stamp time.Time)
  + SetSentAt (stamp time.Time)
  + Update (opts ...QueryOption) string
}

class "email.model.Migrations" {
  + Project: string
  + Filename: string
  + StatementIndex: int64
  + Status: string
  + Delete (opts ...QueryOption) string
  + GetFilename () string
  + GetProject () string
  + GetStatementIndex () int64
  + GetStatus () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + Update (opts ...QueryOption) string
}

class "email.model.QueryConfig" {
  + Table: string
  + Columns: []string
  + Where: string
  + OrderBy: string
  + LimitStart: int
  + LimitOffset: int
  + Statement: string
  + Apply (opts ...QueryOption) *QueryConfig
  + WithColumns (cols []string) QueryOption
  + WithLimit (start,offset int) QueryOption
  + WithOrderBy (clause string) QueryOption
  + WithStatement (stmt string) QueryOption
  + WithTable (name string) QueryOption
  + WithWhere (clause string) QueryOption
}

interface "email.model.QueryOption" {
  + WithTable: WithTable (name string) QueryOption
  + WithColumns: WithColumns (cols []string) QueryOption
  + WithWhere: WithWhere (clause string) QueryOption
  + WithOrderBy: WithOrderBy (clause string) QueryOption
  + WithLimit: WithLimit (start,offset int) QueryOption
  + WithStatement: WithStatement (stmt string) QueryOption
}

class "email.smtp.Config" {
  + Host: string
  + Port: int
  + Username: string
  + Password: string
  + From: string
}

class "email.smtp.SMTPSender" {
  - config: Config
  + Send (recipient,subject,body string) error
}

interface "email.smtp.Sender" {
  + Send: Send (recipient,subject,body string) error
}

class "email.storage.EmailStorage" {
  - db: *sqlx.DB
  + Create (ctx context.Context, email *model.Email) error
  + Get (ctx context.Context, id string) (*model.Email, error)
  + GetFailed (ctx context.Context, limit int) ([]model.Email, error)
  + GetPending (ctx context.Context, limit int) ([]model.Email, error)
  + GetSent (ctx context.Context, limit int) ([]model.Email, error)
  + Update (ctx context.Context, email *model.Email) error
}

interface "email.EmailStorage" {
  + Create: Create (ctx context.Context, email *model.Email) error
  + Get: Get (ctx context.Context, id string) (*model.Email, error)
  + GetPending: GetPending (ctx context.Context, limit int) ([]model.Email, error)
  + Update: Update (ctx context.Context, email *model.Email) error
}

class "email.Handler" {
  - service: *Service
  + Mount (_ context.Context, r platform.Router) error
  + Name () string
  + Start (ctx context.Context) error
  + Stop (ctx context.Context) error
}

class "email.Service" {
  - emailStorage: EmailStorage
  - sender: smtp.Sender
  - queue: chan *model.Email
  - wg: sync.WaitGroup
  - ctx: context.Context
  - cancel: context.CancelFunc
  - ticker: *time.Ticker
  - options: ServiceOptions
  - logger: *slog.Logger
  + AddEmail (ctx context.Context, email *model.Email) error
  + Start ()
  + Stop ()
}

class "email.ServiceOptions" {
  + MaxRetries: int64
  + RetryDuration: time.Duration
  + TickerInterval: time.Duration
  + QueueCapacity: int64
  + Logger: *slog.Logger
}

class "expvar.Handler" {
  + Enabled: bool
  + Mount (_ context.Context, r platform.Router) error
  + Name () string
  + Start (context.Context) error
}

class "cms.Field" {
  + Name: string
  + Title: string
  + Desc: string
  + Type: string
  + Value: any
  + Placeholder: string
  + Required: bool
  + Options: []Option
  + Attributes: map[string]string
  + Size: string
  + Height: int
  + Rows: int
  + Cols: int
  + Link: string
  + Sort: string
  + Accept: string
  + Multiple: bool
  + Disabled: bool
  + Readonly: bool
  + Error: string
  + Help: string
}

class "cms.Form" {
  + Name: string
  + Title: string
  + Fields: []Field
  + Meta: map[string]string
  + UnmarshalYAML (node *yaml.Node) error
}

class "cms.Navigation" {
  + Name: string
  + Links: []NavigationLink
}

class "cms.NavigationLink" {
  + Label: string
  + URL: string
  + Icon: string
}

class "cms.Option" {
  + Value: string
  + Label: string
}

class "cms.RenderData" {
  + Title: string
  + Description: string
  + Fields: []Field
  + Method: string
  + Action: string
  + SubmitLabel: string
  + CancelURL: string
  + CancelLabel: string
  + Navigation: *Navigation
  + FieldsBySize (size string) []Field
  + FieldsWithType (fieldType string) []Field
  + HiddenFields () []Field
  + SetAction (action string) *RenderData
  + SetCancelLabel (label string) *RenderData
  + SetCancelURL (url string) *RenderData
  + SetMethod (method string) *RenderData
  + SetSubmitLabel (label string) *RenderData
  + VisibleFields () []Field
}

class "cms.schema.Column" {
  + Name: string
  + Type: string
  + Key: string
  + Comment: string
  + DataType: string
  + Values: []string
  + EnumValues: []string
  + DefaultVal: string
  + Nullable: bool
  + Attributes: map[string]string
  + GetFieldType () string
  + GetLabel () string
  + IsEnum () bool
  + IsIndexed () bool
  + IsPrimaryKey () bool
  + IsTimestamp () bool
}

class "cms.schema.Index" {
  + Name: string
  + Columns: []string
  + Primary: bool
  + Unique: bool
}

class "cms.schema.Schema" {
  + Tables: []*Table
  + GetTable (name string) *Table
  + GetTableNames () []string
  + Walk (cb func(t *Table))
}

class "cms.schema.Table" {
  + Name: string
  + Comment: string
  + Columns: []*Column
  + Indexes: []*Index
}

class "maillist.storage.Permissions" {
  + User: *usermodel.User
  + Create: bool
}

class "maillist.MailList" {
  + Create (w http.ResponseWriter, r *http.Request)
  + Index (w http.ResponseWriter, r *http.Request)
  + Mount (r platform.Router) error
  + Name () string
  + Start (ctx context.Context) error
}

class "maillist.model.Maillist" {
  + ID: string
  + Name: string
  + Slug: string
  + Description: string
  + CreatedAt: *time.Time
  + UpdatedAt: *time.Time
  + GetCreatedAt () *time.Time
  + GetDescription () string
  + GetID () string
  + GetName () string
  + GetSlug () string
  + GetUpdatedAt () *time.Time
  + SetCreatedAt (stamp time.Time)
  + SetUpdatedAt (stamp time.Time)
}

class "maillist.model.MaillistCampaign" {
  + ID: string
  + MaillistID: string
  + Subject: string
  + Body: string
  + Status: string
  + ScheduledAt: *time.Time
  + SentAt: *time.Time
  + CreatedAt: *time.Time
  + UpdatedAt: *time.Time
  + GetBody () string
  + GetCreatedAt () *time.Time
  + GetID () string
  + GetMaillistID () string
  + GetScheduledAt () *time.Time
  + GetSentAt () *time.Time
  + GetStatus () string
  + GetSubject () string
  + GetUpdatedAt () *time.Time
  + SetCreatedAt (stamp time.Time)
  + SetScheduledAt (stamp time.Time)
  + SetSentAt (stamp time.Time)
  + SetUpdatedAt (stamp time.Time)
}

class "maillist.model.MaillistMember" {
  + ID: string
  + MaillistID: string
  + Email: string
  + Name: string
  + SubscribedAt: *time.Time
  + UnsubscribedAt: *time.Time
  + Source: string
  + GetEmail () string
  + GetID () string
  + GetMaillistID () string
  + GetName () string
  + GetSource () string
  + GetSubscribedAt () *time.Time
  + GetUnsubscribedAt () *time.Time
  + SetSubscribedAt (stamp time.Time)
  + SetUnsubscribedAt (stamp time.Time)
}

class "maillist.model.MaillistMemberActivity" {
  + ID: string
  + MaillistMemberID: string
  + CampaignID: string
  + ActivityType: string
  + ActivityAt: *time.Time
  + GetActivityAt () *time.Time
  + GetActivityType () string
  + GetCampaignID () string
  + GetID () string
  + GetMaillistMemberID () string
  + SetActivityAt (stamp time.Time)
}

class "maillist.model.Migrations" {
  + Project: string
  + Filename: string
  + StatementIndex: int32
  + Status: string
  + GetFilename () string
  + GetProject () string
  + GetStatementIndex () int32
  + GetStatus () string
}

class "pulse.storage.Storage" {
  - db: *sqlx.DB
  + Pulse (ctx context.Context, count int64) error
}

class "pulse.service.Handlers" {
  + IndexPage (w http.ResponseWriter, r *http.Request)
  + Mount (r platform.Router)
  + PostIngest (w http.ResponseWriter, r *http.Request)
  + UserPage (w http.ResponseWriter, r *http.Request)
}

class "pulse.service.Options" {
  + Path: string
}

class "pulse.service.PulseModule" {
  + Mount (ctx context.Context, r platform.Router) error
  + Name () string
}

class "pulse.model.Migrations" {
  + Project: string
  + Filename: string
  + StatementIndex: int64
  + Status: string
  + Delete (opts ...QueryOption) string
  + GetFilename () string
  + GetProject () string
  + GetStatementIndex () int64
  + GetStatus () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + Update (opts ...QueryOption) string
}

class "pulse.model.PulseDaily" {
  + UserID: string
  + Stamp: *time.Time
  + Count: int64
  + Delete (opts ...QueryOption) string
  + GetCount () int64
  + GetStamp () *time.Time
  + GetUserID () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetStamp (stamp time.Time)
  + Update (opts ...QueryOption) string
}

class "pulse.model.PulseHourly" {
  + UserID: string
  + Stamp: *time.Time
  + Count: int64
  + Delete (opts ...QueryOption) string
  + GetCount () int64
  + GetStamp () *time.Time
  + GetUserID () string
  + Insert (opts ...QueryOption) string
  + Select (opts ...QueryOption) string
  + SetStamp (stamp time.Time)
  + Update (opts ...QueryOption) string
}

class "pulse.model.QueryConfig" {
  + Table: string
  + Columns: []string
  + Where: string
  + OrderBy: string
  + LimitStart: int
  + LimitOffset: int
  + Statement: string
  + Apply (opts ...QueryOption) *QueryConfig
  + WithColumns (cols []string) QueryOption
  + WithLimit (start,offset int) QueryOption
  + WithOrderBy (clause string) QueryOption
  + WithStatement (stmt string) QueryOption
  + WithTable (name string) QueryOption
  + WithWhere (clause string) QueryOption
}

interface "pulse.model.QueryOption" {
  + WithTable: WithTable (name string) QueryOption
  + WithColumns: WithColumns (cols []string) QueryOption
  + WithWhere: WithWhere (clause string) QueryOption
  + WithOrderBy: WithOrderBy (clause string) QueryOption
  + WithLimit: WithLimit (start,offset int) QueryOption
  + WithStatement: WithStatement (stmt string) QueryOption
}

class "user.cmd.generate.Config" {
  + Features: map[string]any
  + Flows: map[string]Flow
}

class "user.cmd.generate.Flow" {
  + Steps: []Step
}

class "user.cmd.generate.Step" {
  + Name: string
  + View: string
  + Link: string
  + EnabledIf: string
  + Next: map[string]string
}


interface "Campaign"


"blog.model.ArticleList" --> "blog.model.Article" : .Articles






"blog.storage.Storage" --> "blog.model.Article" : .GetArticleBySlug()
"blog.storage.Storage" --> "blog.model.Article" : .GetArticles()
"blog.storage.Storage" --> "blog.model.Article" : .InsertArticle()
"blog.storage.Storage" --> "blog.model.Article" : .SearchArticles()
"blog.view.IndexData" --> "blog.model.Article" : .Articles
"blog.view.IndexData" --> "blog.view.any" : .Data



"blog.view.Views" --> "blog.view.Loader" : .Loader

"blog.view.Views" --> "blog.model.Article" : .AtomFeed()
"blog.handlers.Handlers" --> "blog.storage.Storage" : .repository
"blog.handlers.Handlers" --> "blog.view.Views" : .views

"blog.handlers.Handlers" --> "blog.storage.Storage" : .Repository()
"blog.handlers.Handlers" --> "blog.view.Views" : .Views()
"blog.Generator" --> "blog.Module" : .module

"blog.Generator" --> "blog.handlers.Handlers" : .generateArticlePage()
"blog.Generator" --> "blog.handlers.Handlers" : .generateFeed()
"blog.Generator" --> "blog.handlers.Handlers" : .generateIndexPage()
"blog.Generator" --> "blog.handlers.Handlers" : .generateStaticPages()
"blog.Generator" --> "blog.handlers.Handlers" : .walkPages()
"blog.Module" --> "blog.storage.Storage" : .repository
"blog.Module" --> "blog.model.Article" : .articles

"blog.Module" --> "blog.storage.Storage" : .SetRepository()
"blog.Module" --> "blog.model.Article" : .parseMarkdownFile()




"user.model.UserAuth" --> "user.model.User" : .UserID (1:1)


"user.model.UserGroupMember" --> "user.model.UserGroup" : .UserGroupID (1:1)
"user.model.UserGroupMember" --> "user.model.User" : .UserID (1:1)

"user.model.UserSession" --> "user.model.User" : .UserID (1:N)






"daily.model.Todo" --> "daily.model.User" : .UserID (1:N)

"daily.model.User" --> "user.model.User" : .type


"user.storage.SessionStorage" --> "user.model.UserSession" : .Create()
"user.storage.SessionStorage" --> "user.model.UserSession" : .Get()

"user.storage.UserStorage" --> "user.model.User" : .Authenticate()
"user.storage.UserStorage" --> "user.model.User" : .Create()
"user.storage.UserStorage" --> "user.model.User" : .Get()
"user.storage.UserStorage" --> "user.model.UserGroup" : .GetGroups()
"user.storage.UserStorage" --> "user.model.User" : .Update()
"user.view.Renderer" --> "user.view.any" : .data

"user.view.Data" --> "user.model.User" : .SessionUser

"user.view.LoginData" --> "user.model.User" : .SessionUser

"user.view.LogoutData" --> "user.model.User" : .SessionUser

"user.view.RegisterData" --> "user.model.User" : .SessionUser

"user.service.Service" --> "user.storage.UserStorage" : .UserStorage
"user.service.Service" --> "user.storage.SessionStorage" : .SessionStorage
"user.service.Service" --> "user.view.Renderer" : .view

"user.Handler" --|> "user.service.Service" : embeds


"daily.storage.Storage" --> "daily.model.Todo" : .Add()
"daily.storage.Storage" --> "daily.model.Todo" : .Get()
"daily.storage.Storage" --> "daily.model.Todo" : .List()
"daily.storage.Storage" --> "daily.model.Todo" : .Update()
"daily.view.Data" --> "daily.model.Todo" : .Tasks
"daily.view.Data" --> "daily.model.User" : .SessionUser


"daily.view.Views" --> "daily.view.Loader" : .Loader

"daily.Module" --> "daily.storage.Storage" : .repository
"daily.Module" --> "daily.view.Views" : .views








"email.smtp.SMTPSender" --> "email.smtp.Config" : .config



"email.storage.EmailStorage" --> "email.model.Email" : .Create()
"email.storage.EmailStorage" --> "email.model.Email" : .Get()
"email.storage.EmailStorage" --> "email.model.Email" : .GetFailed()
"email.storage.EmailStorage" --> "email.model.Email" : .GetPending()
"email.storage.EmailStorage" --> "email.model.Email" : .GetSent()
"email.storage.EmailStorage" --> "email.model.Email" : .Update()

"email.Handler" --> "email.Service" : .service

"email.Service" --> "email.EmailStorage" : .emailStorage
"email.Service" --> "email.smtp.Sender" : .sender
"email.Service" --> "email.ServiceOptions" : .options

"email.Service" --> "email.model.Email" : .AddEmail()
"email.Service" --> "email.model.Email" : .sendEmail()


"cms.Field" --> "cms.any" : .Value
"cms.Field" --> "cms.Option" : .Options

"cms.Form" --> "cms.Field" : .Fields

"cms.Navigation" --> "cms.NavigationLink" : .Links



"cms.RenderData" --> "cms.Field" : .Fields
"cms.RenderData" --> "cms.Navigation" : .Navigation



"cms.schema.Schema" --> "cms.schema.Table" : .Tables

"cms.schema.Table" --> "cms.schema.Column" : .Columns
"cms.schema.Table" --> "cms.schema.Index" : .Indexes

"maillist.storage.Permissions" --> "user.model.User" : .User



"maillist.model.MaillistCampaign" --> "maillist.model.Maillist" : .MaillistID (1:N)

"maillist.model.MaillistMember" --> "maillist.model.Maillist" : .MaillistID (1:N)

"maillist.model.MaillistMemberActivity" --> "maillist.model.MaillistMember" : .MaillistMemberID (1:N)
"maillist.model.MaillistMemberActivity" --> "maillist.model.Campaign" : .CampaignID (1:N)



"pulse.service.Handlers" --|> "pulse.service.Options" : embeds


"pulse.service.PulseModule" --|> "pulse.service.Options" : embeds


"pulse.model.PulseDaily" --> "pulse.model.User" : .UserID (1:1)

"pulse.model.PulseHourly" --> "pulse.model.User" : .UserID (1:1)



"user.cmd.generate.Config" --> "user.cmd.generate.any" : .Features
"user.cmd.generate.Config" --> "user.cmd.generate.Flow" : .Flows

"user.cmd.generate.Flow" --> "user.cmd.generate.Step" : .Steps



@enduml
